version: '2.0'
services:
  background-jobs:
    build: .
    command: bin/runner
    volumes:
      - .:/usr/src/app
      - background-jobs-bundle:/bundle
    links:
      - rabbitmq:amqp
    env_file:
      - .env
  rabbitmq:
    build:
      context: .
      dockerfile: Dockerfile.rabbitmq
    ports:
      - 15672:15672
  ridesharing-lyft:
    build:
      context: ../ridesharing-lyft
    volumes:
      - ../ridesharing-lyft:/usr/src/app
      - ridesharing-lyft-bundle:/bundle
    links:
      - rabbitmq:amqp
volumes:
  background-jobs-bundle: {}
  ridesharing-lyft-bundle: {}
