FROM rabbitmq:3-management

RUN apt-get update && apt-get -y -q install wget

RUN wget http://www.rabbitmq.com/community-plugins/v3.6.x/rabbitmq_delayed_message_exchange-0.0.1.ez

RUN cp rabbitmq_delayed_message_exchange-0.0.1.ez /usr/lib/rabbitmq/lib/rabbitmq_server-3.6.6/plugins/

RUN rabbitmq-plugins enable --offline rabbitmq_delayed_message_exchange
